# Misc constants
DOT = '.'
PIPE = '|'
SLASH = '/'
XML_EXTENSION = DOT + 'xml'
VERSION_STR = 'v'
ID_STR = 'id:'
PUBLISH_OP = 'ws_publish'
UNPUBLISH_OP = 'ws_unpublish'
LATEST_STR = 'latest'
NC_EXTENSION = '.nc'

# IDs & Keys
MASTER_ID = 'master_id'
ID = 'id'
DATASET_ID = 'dataset_id'
INSTANCE_ID = 'instance_id'
DRS_ID = 'drs_id'
PROJECT_ID = 'project_id'
PROJECT = 'project'
VERSION = 'Version'
ID_DICT = 'id_dictionary'
VARIABLE = 'variable'
VARIABLES = 'variables'
G_ATTR = 'global_attributes'
NODE_INFO = 'node_info'
IS_FILE = 'is_file'
FIELD = 'field'
DOC = 'doc'

# Entities
DATASET = 'dataset'
NODE = 'node'
FILE = 'File'
NETCDF_FILES = 'netCDFFiles'
RECORD = 'record'
